<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8GvzLy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8GvzLy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8GvzLy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8GvzLy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV8GvzLy\App_KernelDevDebugContainer([
    'container.build_hash' => 'V8GvzLy',
    'container.build_id' => 'ee609a76',
    'container.build_time' => 1666787485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8GvzLy');
