<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCoK6BpW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCoK6BpW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCoK6BpW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCoK6BpW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCoK6BpW\App_KernelDevDebugContainer([
    'container.build_hash' => 'CoK6BpW',
    'container.build_id' => '793138f1',
    'container.build_time' => 1666697907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCoK6BpW');
