<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSYOUvsL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSYOUvsL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSYOUvsL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSYOUvsL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSYOUvsL\App_KernelDevDebugContainer([
    'container.build_hash' => 'SYOUvsL',
    'container.build_id' => '1abfdbbc',
    'container.build_time' => 1666615464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSYOUvsL');
